export const actionTypes = {
    ADD_PEOPLE: "ADD_PEOPLE",
    TOOGLE_SUPERUSER: "TOOGLE_SUPERUSER",
    FLIP: "FLIP",
    FLIPSUPERUSER: "FLIPSUPERUSER",
    ADD_ENTITIES: "ADD_ENTITIES",
    ADD_KEYS: "ADD_KEYS"
}
