export const actionTypes = {
    ADD_PEOPLE: "ADD_PEOPLE",
    TOGGLE_SUPERUSER: "TOGGLE_SUPERUSER",
    FLIP: "FLIP",
    FLIPSUPERUSER: "FLIPSUPERUSER",
    ADD_ENTITIES: "ADD_ENTITIES",
    ADD_KEYS: "ADD_KEYS",
    ADD_PERSON: "ADD_PERSON"
}
